const PERMISSIONS = Object.freeze({
  SUMMARY_READ: 'summary.read', USERS_READ_DIRECTORY: 'users.readDirectory', USERS_MANAGE: 'users.manage', USERS_MANAGE_SERVICES: 'users.manageServices',
  PATIENTS_READ_ALL: 'patients.readAll', PATIENTS_READ_LINKED: 'patients.readLinked', PATIENTS_CREATE: 'patients.create', PATIENTS_UPDATE_ALL: 'patients.updateAll',
  PATIENTS_UPDATE_LINKED: 'patients.updateLinked', PATIENTS_MANAGE_STATE: 'patients.manageState', PATIENTS_MANAGE_LINKS: 'patients.manageLinks',
  PATIENTS_LINK_FROM_LINKED: 'patients.linkFromLinked', APPOINTMENTS_READ_ALL: 'appointments.readAll', APPOINTMENTS_MANAGE_ALL: 'appointments.manageAll',
  APPOINTMENTS_MANAGE_OWN: 'appointments.manageOwn', APPOINTMENTS_READ_AVAILABILITY: 'appointments.readAvailability',
  APPOINTMENTS_READ_INTERNAL_ALL: 'appointments.readInternalNotesAll', APPOINTMENTS_READ_INTERNAL_OWN: 'appointments.readInternalNotesOwn',
  REPORTS_READ_ALL: 'reports.readAll', REPORTS_READ_LINKED: 'reports.readLinked', REPORTS_CREATE_ANY: 'reports.createAny', REPORTS_CREATE_LINKED: 'reports.createLinked',
  REPORTS_MANAGE_OWN: 'reports.manageOwnDraft', CONVERSATIONS_MANAGE_OWN: 'conversations.manageOwn', SERVICES_READ: 'services.read', SERVICES_MANAGE: 'services.manage',
  CATALOGS_READ: 'catalogs.read', CATALOGS_MANAGE: 'catalogs.manage', AUDIT_READ: 'audit.read'
});

const ROLE_PERMISSIONS = Object.freeze({
  administrador: [PERMISSIONS.SUMMARY_READ, PERMISSIONS.USERS_READ_DIRECTORY, PERMISSIONS.USERS_MANAGE, PERMISSIONS.USERS_MANAGE_SERVICES, PERMISSIONS.PATIENTS_READ_ALL, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_UPDATE_ALL, PERMISSIONS.PATIENTS_MANAGE_STATE, PERMISSIONS.PATIENTS_MANAGE_LINKS, PERMISSIONS.APPOINTMENTS_READ_ALL, PERMISSIONS.APPOINTMENTS_MANAGE_ALL, PERMISSIONS.APPOINTMENTS_READ_AVAILABILITY, PERMISSIONS.REPORTS_READ_ALL, PERMISSIONS.CONVERSATIONS_MANAGE_OWN, PERMISSIONS.SERVICES_READ, PERMISSIONS.SERVICES_MANAGE, PERMISSIONS.CATALOGS_READ, PERMISSIONS.CATALOGS_MANAGE, PERMISSIONS.AUDIT_READ],
  coordinacion: [PERMISSIONS.SUMMARY_READ, PERMISSIONS.USERS_READ_DIRECTORY, PERMISSIONS.USERS_MANAGE_SERVICES, PERMISSIONS.PATIENTS_READ_ALL, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_UPDATE_ALL, PERMISSIONS.PATIENTS_MANAGE_STATE, PERMISSIONS.PATIENTS_MANAGE_LINKS, PERMISSIONS.APPOINTMENTS_READ_ALL, PERMISSIONS.APPOINTMENTS_MANAGE_ALL, PERMISSIONS.APPOINTMENTS_READ_AVAILABILITY, PERMISSIONS.APPOINTMENTS_READ_INTERNAL_ALL, PERMISSIONS.REPORTS_READ_ALL, PERMISSIONS.REPORTS_CREATE_ANY, PERMISSIONS.REPORTS_MANAGE_OWN, PERMISSIONS.CONVERSATIONS_MANAGE_OWN, PERMISSIONS.SERVICES_READ, PERMISSIONS.CATALOGS_READ],
  secretaria: [PERMISSIONS.SUMMARY_READ, PERMISSIONS.USERS_READ_DIRECTORY, PERMISSIONS.USERS_MANAGE_SERVICES, PERMISSIONS.PATIENTS_READ_ALL, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_UPDATE_ALL, PERMISSIONS.PATIENTS_MANAGE_STATE, PERMISSIONS.PATIENTS_MANAGE_LINKS, PERMISSIONS.APPOINTMENTS_READ_ALL, PERMISSIONS.APPOINTMENTS_MANAGE_ALL, PERMISSIONS.APPOINTMENTS_READ_AVAILABILITY, PERMISSIONS.REPORTS_READ_ALL, PERMISSIONS.CONVERSATIONS_MANAGE_OWN, PERMISSIONS.SERVICES_READ, PERMISSIONS.CATALOGS_READ],
  profesional: [PERMISSIONS.SUMMARY_READ, PERMISSIONS.USERS_READ_DIRECTORY, PERMISSIONS.PATIENTS_READ_LINKED, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_UPDATE_LINKED, PERMISSIONS.PATIENTS_LINK_FROM_LINKED, PERMISSIONS.APPOINTMENTS_MANAGE_OWN, PERMISSIONS.APPOINTMENTS_READ_AVAILABILITY, PERMISSIONS.APPOINTMENTS_READ_INTERNAL_OWN, PERMISSIONS.REPORTS_READ_LINKED, PERMISSIONS.REPORTS_CREATE_LINKED, PERMISSIONS.REPORTS_MANAGE_OWN, PERMISSIONS.CONVERSATIONS_MANAGE_OWN, PERMISSIONS.SERVICES_READ, PERMISSIONS.CATALOGS_READ]
});

module.exports = { PERMISSIONS, ROLE_PERMISSIONS };
