/** Coordina participantes, lectura y archivado con bloqueos para conservar consistencia concurrente. */
const { Op, QueryTypes } = require('sequelize'); const AppError = require('../../shared/errors/AppError'); const { sequelize, Asunto, Conversacion, ConversacionParticipante, Mensaje, Paciente, Usuario } = require('../../shared/database/models'); const { getPagination, paginationMeta } = require('../../shared/utils/pagination'); const audit = require('../auditoria/auditoria.service'); const auth = require('../auth/auth.service'); const messageService = require('./mensaje.service'); const policy = require('./mensajeria.policy');
const fail = (code, message, status) => { throw new AppError({ code, message, status }); };
const baseInclude = [{ model: Asunto, as: 'asunto', attributes: ['id', 'codigo', 'nombre'] }, { model: Paciente, as: 'paciente', attributes: ['id', 'nombre', 'apellido'], required: false }, { model: Usuario, as: 'participantes', attributes: ['id', 'nombre', 'apellido', 'fotoUrl'], through: { attributes: ['ultimoMensajeLeidoId', 'archivadoAt'] } }];
const participant = (row) => ({ id: row.id, nombreCompleto: `${row.nombre} ${row.apellido}`, fotoUrl: row.fotoUrl });
const unreadCount = async (conversationId, state, transaction) => { const read = state.ultimoMensajeLeidoId ? await Mensaje.findByPk(state.ultimoMensajeLeidoId, { transaction }) : null; return Mensaje.count({ where: { conversacionId: conversationId, remitenteId: { [Op.ne]: state.usuarioId }, ...(read ? { [Op.or]: [{ createdAt: { [Op.gt]: read.createdAt } }, { createdAt: read.createdAt, id: { [Op.gt]: read.id } }] } : {}) }, transaction }); };
const detail = (row, state) => ({ id: row.id, titulo: row.titulo, asunto: { id: row.asunto.id, codigo: row.asunto.codigo, nombre: row.asunto.nombre }, paciente: row.paciente ? { id: row.paciente.id, nombre: row.paciente.nombre, apellido: row.paciente.apellido } : null, participantes: row.participantes.map(participant), archivada: Boolean(state.archivadoAt), ultimoMensajeLeidoId: state.ultimoMensajeLeidoId, createdAt: row.createdAt, updatedAt: row.updatedAt });
const load = async (actor, id, options = {}) => { const state = await policy.requireParticipation(actor, id, options); const row = await Conversacion.findByPk(id, { include: baseInclude, transaction: options.transaction }); if (!row) fail('CONVERSACION_NO_ENCONTRADA', 'Conversación no encontrada.', 404); return { row, state }; };
const get = async (actor, id) => { const { row, state } = await load(actor, id); return detail(row, state); };
const list = async (actor, query) => {
  const states = await ConversacionParticipante.findAll({ where: { usuarioId: actor.id, archivadoAt: query.archivada ? { [Op.not]: null } : null } });
  const stateByConversation = new Map(states.map((state) => [state.conversacionId, state]));
  let ids = [...stateByConversation.keys()];
  if (query.soloNoLeidas) {
    const unreadIds = [];
    for (const id of ids) if (await unreadCount(id, stateByConversation.get(id)) > 0) unreadIds.push(id);
    ids = unreadIds;
  }
  if (query.search && ids.length) {
    const matches = await sequelize.query("SELECT DISTINCT c.id FROM conversaciones c LEFT JOIN conversaciones_participantes cp ON cp.conversacion_id = c.id LEFT JOIN usuarios u ON u.id = cp.usuario_id WHERE c.id IN (:ids) AND (c.titulo ILIKE :search OR concat_ws(' ', u.nombre, u.apellido) ILIKE :search)", { replacements: { ids, search: `%${query.search}%` }, type: QueryTypes.SELECT });
    ids = matches.map((row) => row.id);
  }
  const where = { id: { [Op.in]: ids } };
  if (query.asuntoId) where.asuntoId = query.asuntoId;
  if (query.pacienteId) where.pacienteId = query.pacienteId;
  const { page, limit, offset } = getPagination(query);
  const { rows, count } = await Conversacion.findAndCountAll({ where, limit, offset, order: [[query.sort, query.order.toUpperCase()], ['id', query.order.toUpperCase()]] });
  const data = [];
  for (const basic of rows) {
    const loaded = await load(actor, basic.id);
    const last = await Mensaje.findOne({ where: { conversacionId: basic.id }, include: [messageService.includeSender], order: [['createdAt', 'DESC'], ['id', 'DESC']] });
    const noLeidos = await unreadCount(basic.id, loaded.state);
    data.push({ ...detail(loaded.row, loaded.state), ultimoMensaje: last ? { id: last.id, remitente: `${last.remitente.nombre} ${last.remitente.apellido}`, preview: last.contenido.slice(0, 120), createdAt: last.createdAt } : null, noLeidos });
  }
  return { data, meta: paginationMeta({ page, limit, total: count }) };
};
const create = (actor, data, req) => sequelize.transaction(async (transaction) => { const ids = [...new Set(data.participanteIds)]; if (ids.includes(actor.id)) fail('VALIDATION_ERROR', 'No incluyas al creador entre los destinatarios.', 400); if (!ids.length) fail('CONVERSACION_SIN_DESTINATARIOS', 'La conversación requiere destinatarios.', 422); const asunto = await Asunto.findByPk(data.asuntoId, { transaction }); if (!asunto) fail('ASUNTO_NO_ENCONTRADO', 'Asunto no encontrado.', 404); if (!asunto.activo) fail('ASUNTO_INACTIVO', 'Asunto inactivo.', 422); if (data.pacienteId) { const p = await Paciente.findByPk(data.pacienteId, { transaction }); if (!p) fail('PACIENTE_NO_ENCONTRADO', 'Paciente no encontrado.', 404); if (!p.activo) fail('PACIENTE_INACTIVO', 'Paciente inactivo.', 422); } const users = await Usuario.findAll({ where: { id: { [Op.in]: ids } }, transaction, lock: transaction.LOCK.UPDATE }); if (users.length !== ids.length) fail('USUARIO_NO_ENCONTRADO', 'Usuario no encontrado.', 404); if (users.some((u) => !u.activo)) fail('PARTICIPANTE_INACTIVO', 'Un participante está inactivo.', 422); const row = await Conversacion.create({ asuntoId: data.asuntoId, pacienteId: data.pacienteId || null, titulo: data.titulo, creadoPor: actor.id }, { transaction }); const message = await Mensaje.create({ conversacionId: row.id, remitenteId: actor.id, contenido: data.mensajeInicial }, { transaction }); await ConversacionParticipante.bulkCreate([{ conversacionId: row.id, usuarioId: actor.id, ultimoMensajeLeidoId: message.id, ultimaLecturaAt: message.createdAt, agregadoPor: actor.id, joinedAt: new Date() }, ...ids.map((id) => ({ conversacionId: row.id, usuarioId: id, agregadoPor: actor.id, joinedAt: new Date() }))], { transaction }); await audit.record({ actorId: actor.id, action: 'CONVERSACION_CREADA', resource: 'conversacion', resourceId: row.id, metadata: { cantidad: ids.length + 1 }, context: auth.context(req), transaction }); const loaded = await load(actor, row.id, { transaction }); await message.reload({ include: [messageService.includeSender], transaction }); return { conversacion: detail(loaded.row, loaded.state), mensaje: messageService.project(message) }; });
const addParticipants = (actor, id, ids, req) => sequelize.transaction(async (transaction) => { await policy.requireParticipation(actor, id, { transaction, lock: transaction.LOCK.UPDATE }); const existing = await ConversacionParticipante.count({ where: { conversacionId: id, usuarioId: { [Op.in]: ids } }, transaction }); if (existing) fail('PARTICIPANTE_YA_EXISTE', 'Un usuario ya participa en la conversación.', 409); const users = await Usuario.findAll({ where: { id: { [Op.in]: ids } }, transaction, lock: transaction.LOCK.UPDATE }); if (users.length !== ids.length) fail('USUARIO_NO_ENCONTRADO', 'Usuario no encontrado.', 404); if (users.some((u) => !u.activo)) fail('PARTICIPANTE_INACTIVO', 'Un participante está inactivo.', 422); const last = await Mensaje.findOne({ where: { conversacionId: id }, order: [['createdAt', 'DESC'], ['id', 'DESC']], transaction }); await ConversacionParticipante.bulkCreate(ids.map((userId) => ({ conversacionId: id, usuarioId: userId, ultimoMensajeLeidoId: last?.id || null, ultimaLecturaAt: new Date(), agregadoPor: actor.id, joinedAt: new Date() })), { transaction }); await audit.record({ actorId: actor.id, action: 'PARTICIPANTE_AGREGADO', resource: 'conversacion', resourceId: id, metadata: { cantidad: ids.length }, context: auth.context(req), transaction }); return users.map(participant); });
const markRead = (actor, id, messageId) => sequelize.transaction(async (transaction) => { const state = await policy.requireParticipation(actor, id, { transaction, lock: transaction.LOCK.UPDATE }); const message = await Mensaje.findByPk(messageId, { transaction }); if (!message) fail('MENSAJE_NO_ENCONTRADO', 'Mensaje no encontrado.', 404); if (message.conversacionId !== id) fail('MENSAJE_NO_PERTENECE_CONVERSACION', 'El mensaje no pertenece a la conversación.', 422); if (state.ultimoMensajeLeidoId) { const current = await Mensaje.findByPk(state.ultimoMensajeLeidoId, { transaction }); if (current && (message.createdAt < current.createdAt || (+message.createdAt === +current.createdAt && message.id < current.id))) fail('LECTURA_NO_PUEDE_RETROCEDER', 'La lectura no puede retroceder.', 409); } await state.update({ ultimoMensajeLeidoId: message.id, ultimaLecturaAt: new Date() }, { transaction }); return { ultimoMensajeLeidoId: message.id, ultimaLecturaAt: state.ultimaLecturaAt, noLeidos: await unreadCount(id, state, transaction) }; });
const archive = (actor, id, active, req) => sequelize.transaction(async (transaction) => { const state = await policy.requireParticipation(actor, id, { transaction, lock: transaction.LOCK.UPDATE }); await state.update({ archivadoAt: active ? new Date() : null }, { transaction }); await audit.record({ actorId: actor.id, action: active ? 'CONVERSACION_ARCHIVADA' : 'CONVERSACION_DESARCHIVADA', resource: 'conversacion', resourceId: id, context: auth.context(req), transaction }); });
const unreadSummary = async (actor, limit) => { const states = await ConversacionParticipante.findAll({ where: { usuarioId: actor.id }, include: [{ model: Conversacion, as: 'conversacion', include: [{ model: Usuario, as: 'participantes', attributes: ['nombre', 'apellido'], through: { attributes: [] } }] }], order: [[{ model: Conversacion, as: 'conversacion' }, 'updatedAt', 'DESC']] }); const items = []; for (const state of states) { if (await unreadCount(state.conversacionId, state) > 0) items.push({ id: state.conversacion.id, titulo: state.conversacion.titulo, updatedAt: state.conversacion.updatedAt, participantes: state.conversacion.participantes.map((u) => `${u.nombre} ${u.apellido}`) }); } return { count: items.length, items: items.slice(0, limit) }; };
module.exports = { list, get, create, addParticipants, markRead, archive, unreadSummary };
