module.exports = Object.freeze([
  'LOGIN_EXITOSO', 'LOGIN_FALLIDO', 'SESION_RENOVADA', 'LOGOUT', 'LOGOUT_TODAS', 'USUARIO_CREADO', 'USUARIO_EDITADO', 'USUARIO_ACTIVADO',
  'USUARIO_DESACTIVADO', 'ACCESO_RESTABLECIDO', 'USUARIO_FOTO_ACTUALIZADA', 'USUARIO_FOTO_ELIMINADA', 'PACIENTE_CREADO', 'PACIENTE_EDITADO',
  'PACIENTE_ACTIVADO', 'PACIENTE_DESACTIVADO', 'PRESTADOR_VINCULADO', 'PRESTADOR_VINCULADO_AUTOMATICAMENTE', 'PRESTADOR_DESVINCULADO',
  'SERVICIO_ASIGNADO', 'SERVICIO_QUITADO', 'CATALOGO_CREADO', 'CATALOGO_EDITADO', 'CATALOGO_ACTIVADO', 'CATALOGO_DESACTIVADO',
  'SERVICIO_IMAGEN_ACTUALIZADA', 'SERVICIO_IMAGEN_ELIMINADA', 'TURNO_CREADO', 'TURNO_CONFIRMADO', 'TURNO_CANCELADO', 'TURNO_COMPLETADO',
  'TURNO_AUSENTE', 'TURNO_OBSERVACION_EDITADA', 'TURNO_NOTA_INTERNA_EDITADA', 'INFORME_CREADO', 'INFORME_EDITADO', 'INFORME_FINALIZADO',
  'INFORME_VISUALIZADO', 'CONVERSACION_CREADA', 'PARTICIPANTE_AGREGADO', 'MENSAJE_ENVIADO', 'CONVERSACION_ARCHIVADA', 'CONVERSACION_DESARCHIVADA'
]);
