export const siteConfig = Object.freeze({
  name: 'C.E.I.T. Mentes Luminosas',
  shortName: 'Mentes Luminosas',
  tagline: 'Acompañamiento interdisciplinario para cada etapa del desarrollo.',
  description: 'Centro Educativo Interdisciplinario Terapéutico orientado al acompañamiento de niños, adolescentes y sus familias.',
  location: 'Goya, Corrientes',
  address: '',
  schedule: '',
  phone: '',
  whatsapp: '',
  email: '',
  mapEmbedUrl: '',
  directionsUrl: '',
  social: { instagram: '', facebook: '' },
  coverages: [],
  images: {
    logo: '/images/branding/logo.png',
    homeHero: '/images/institucionales/home-hero.webp',
    homeSupport: '/images/institucionales/home-acompanamiento.webp',
    homeApproach: '/images/institucionales/home-enfoque-interdisciplinario.webp',
    aboutIdentity: '/images/institucionales/nosotros-identidad.webp',
    aboutSpace: '/images/institucionales/nosotros-espacio.webp',
    aboutValues: '/images/institucionales/nosotros-valores.webp',
  },
  seo: {
    home: { path: '/', title: 'Inicio', description: 'Acompañamiento educativo y terapéutico interdisciplinario para niños, adolescentes y familias.' },
    about: { path: '/nosotros', title: 'Nosotros', description: 'Conocé el enfoque, la misión y los valores de Mentes Luminosas.' },
    services: { path: '/servicios', title: 'Servicios', description: 'Conocé los servicios interdisciplinarios disponibles en el centro.' },
    team: { path: '/equipo', title: 'Equipo', description: 'Conocé al equipo interdisciplinario de Mentes Luminosas.' },
    contact: { path: '/contacto', title: 'Contacto', description: 'Canales de contacto y ubicación de Mentes Luminosas.' },
    privacy: { path: '/privacidad', title: 'Privacidad', description: 'Información inicial sobre privacidad y tratamiento responsable de datos.' },
  },
})
