const codes = [
  'VALIDATION_ERROR', 'AUTHENTICATION_REQUIRED', 'FORBIDDEN', 'FORBIDDEN_FILTER', 'NOT_FOUND', 'INTERNAL_ERROR', 'RATE_LIMIT_EXCEEDED',
  'CREDENCIALES_INVALIDAS', 'LOGIN_LIMITE_EXCEDIDO', 'TOKEN_INVALIDO', 'TOKEN_EXPIRADO', 'REFRESH_INVALIDO', 'REFRESH_REUTILIZADO',
  'SESION_REVOCADA', 'SESION_EXPIRADA', 'USUARIO_INACTIVO', 'USUARIO_NO_ENCONTRADO', 'USUARIO_EMAIL_DUPLICADO', 'USUARIO_DNI_DUPLICADO',
  'USUARIO_TIENE_TURNOS_FUTUROS', 'USUARIO_ESTADO_SIN_CAMBIOS', 'USUARIO_NO_ES_PRESTADOR', 'USUARIO_PROYECCION_DENEGADA',
  'USUARIO_AUTOMODIFICACION_DENEGADA', 'ULTIMO_ADMINISTRADOR_REQUERIDO', 'ESPECIALIDAD_REQUERIDA', 'ROL_NO_HABILITADO',
  'ADMINISTRADOR_NO_PUBLICABLE', 'IMAGEN_REQUERIDA', 'IMAGEN_TIPO_INVALIDO', 'IMAGEN_DEMASIADO_GRANDE', 'PACIENTE_NO_ENCONTRADO',
  'PACIENTE_DNI_DUPLICADO', 'PACIENTE_POSIBLE_DUPLICADO', 'PACIENTE_INACTIVO', 'PACIENTE_TIENE_TURNOS_FUTUROS', 'PACIENTE_ESTADO_SIN_CAMBIOS',
  'TUTOR_REQUERIDO', 'CUD_VENCIMIENTO_REQUERIDO', 'CUD_VENCIMIENTO_NO_PERMITIDO', 'FECHA_NACIMIENTO_INVALIDA', 'VINCULO_NO_ENCONTRADO',
  'VINCULO_YA_EXISTE', 'VINCULO_CREACION_DENEGADA', 'VINCULO_TIENE_TURNOS_FUTUROS', 'MOTIVO_DESVINCULACION_REQUERIDO', 'PACIENTE_NO_VINCULADO',
  'SERVICIO_NO_ENCONTRADO', 'SERVICIO_INACTIVO', 'SERVICIO_YA_ASIGNADO', 'SERVICIO_ASIGNACION_NO_ENCONTRADA', 'SERVICIO_CON_TURNOS_FUTUROS',
  'SERVICIO_DESCRIPCION_REQUERIDA', 'CONSULTORIO_NO_ENCONTRADO', 'CONSULTORIO_INACTIVO', 'CONSULTORIO_CON_TURNOS_FUTUROS',
  'PRESTADOR_NO_ENCONTRADO', 'PRESTADOR_INACTIVO', 'CATALOGO_NOMBRE_DUPLICADO', 'CATALOGO_ESTADO_SIN_CAMBIOS', 'CONSULTORIO_CAPACIDAD_INVALIDA',
  'ASUNTO_NO_ENCONTRADO', 'ASUNTO_INACTIVO', 'ASUNTO_CODIGO_DUPLICADO', 'TIPO_INFORME_NO_ENCONTRADO', 'TIPO_INFORME_INACTIVO',
  'TURNO_NO_ENCONTRADO', 'TURNO_PRESTADOR_AJENO', 'TURNO_NOTAS_INTERNAS_DENEGADAS', 'TURNO_CONFLICTO_PRESTADOR',
  'TURNO_CONFLICTO_PACIENTE', 'TURNO_CONFLICTO_CONSULTORIO', 'TURNO_CONFLICTO_HORARIO', 'TURNO_HORARIO_INVALIDO', 'TURNO_FECHA_INVALIDA',
  'TURNO_DURACION_INVALIDA', 'TURNO_TRANSICION_INVALIDA', 'TURNO_TERMINAL_INMUTABLE', 'TURNO_AUN_NO_COMENZO', 'MOTIVO_CANCELACION_REQUERIDO',
  'RANGO_FECHAS_INVALIDO', 'RANGO_FECHAS_EXCEDIDO', 'INFORME_NO_ENCONTRADO', 'INFORME_PACIENTE_NO_VINCULADO', 'INFORME_NO_ES_AUTOR',
  'INFORME_FINALIZADO', 'INFORME_AUTOR_INACTIVO', 'INFORME_VERSION_CONFLICTO', 'CONVERSACION_NO_ENCONTRADA', 'CONVERSACION_SIN_DESTINATARIOS',
  'PARTICIPANTE_INACTIVO', 'PARTICIPANTE_YA_EXISTE', 'MENSAJE_NO_ENCONTRADO', 'MENSAJE_NO_PERTENECE_CONVERSACION',
  'MENSAJE_CONTENIDO_REQUERIDO', 'LECTURA_NO_PUEDE_RETROCEDER'
];

module.exports = Object.freeze(Object.fromEntries(codes.map((code) => [code, code])));
