const { Op } = require('sequelize');
const AppError = require('../../shared/errors/AppError');
const { sequelize, Informe, Paciente, TipoInforme, Usuario, UsuarioPaciente } = require('../../shared/database/models');
const { getPagination, paginationMeta } = require('../../shared/utils/pagination');
const audit = require('../auditoria/auditoria.service');
const auth = require('../auth/auth.service');
const policy = require('./informe.policy');

const include = [{ model: Paciente, as: 'paciente', attributes: ['id', 'nombre', 'apellido'] }, { model: Usuario, as: 'autor', attributes: ['id', 'nombre', 'apellido', 'activo'] }, { model: TipoInforme, as: 'tipoInforme', attributes: ['id', 'nombre', 'activo'] }];
const personSummary = (row) => ({ id: row.id, nombreCompleto: `${row.nombre} ${row.apellido}` });
const editable = (row, actor) => row.estado === 'borrador' && row.autorId === actor.id && row.autor?.activo;
const summary = (row, actor) => ({ id: row.id, titulo: row.titulo, paciente: personSummary(row.paciente), autor: personSummary(row.autor), tipoInforme: { id: row.tipoInforme.id, nombre: row.tipoInforme.nombre }, estado: row.estado, version: row.version, fechaEmision: row.fechaEmision, createdAt: row.createdAt, updatedAt: row.updatedAt, puedeEditar: Boolean(editable(row, actor)), puedeFinalizar: Boolean(editable(row, actor)) });
const detail = (row, actor) => ({ ...summary(row, actor), paciente: { id: row.paciente.id, nombre: row.paciente.nombre, apellido: row.paciente.apellido }, autor: { id: row.autor.id, nombre: row.autor.nombre, apellido: row.autor.apellido }, resumen: row.resumen, contenido: row.contenido });
const fail = (code, message, status) => { throw new AppError({ code, message, status }); };
const linked = (actor, patientId, transaction) => UsuarioPaciente.findOne({ where: { usuarioId: actor.id, pacienteId: patientId, activo: true }, transaction });
const canRead = async (actor, report, transaction) => policy.canReadAll(actor) || Boolean(await linked(actor, report.pacienteId, transaction));
const requireReport = async (actor, id, options = {}) => { const row = await Informe.findByPk(id, { include, ...options }); if (!row || !(await canRead(actor, row, options.transaction))) fail('INFORME_NO_ENCONTRADO', 'Informe no encontrado.', 404); return row; };
const assertAuthorConditions = async (actor, row, transaction) => { if (!policy.isAuthor(actor, row)) fail('INFORME_NO_ES_AUTOR', 'Solo el autor puede modificar el informe.', 403); if (row.estado !== 'borrador') fail('INFORME_FINALIZADO', 'El informe ya está finalizado.', 409); if (!row.autor.activo) fail('INFORME_AUTOR_INACTIVO', 'El autor está inactivo.', 409); if (actor.rol === 'profesional' && !await linked(actor, row.pacienteId, transaction)) fail('INFORME_PACIENTE_NO_VINCULADO', 'El paciente no está vinculado.', 403); };

const list = async (actor, query) => {
  const where = {}; for (const key of ['pacienteId', 'autorId', 'tipoInformeId', 'estado']) if (query[key]) where[key] = query[key];
  const scopedInclude = [...include]; if (!policy.canReadAll(actor)) scopedInclude.push({ model: UsuarioPaciente, as: 'vinculosActivos', required: true, attributes: [], where: { usuarioId: actor.id, activo: true } });
  if (query.search) where[Op.or] = [{ titulo: { [Op.iLike]: `%${query.search}%` } }, { '$paciente.nombre$': { [Op.iLike]: `%${query.search}%` } }, { '$paciente.apellido$': { [Op.iLike]: `%${query.search}%` } }];
  const { page, limit, offset } = getPagination(query); const { rows, count } = await Informe.findAndCountAll({ where, include: scopedInclude, distinct: true, subQuery: false, limit, offset, order: [[query.sort, query.order.toUpperCase()], ['id', query.order.toUpperCase()]] }); return { data: rows.map((row) => summary(row, actor)), meta: paginationMeta({ page, limit, total: count }) };
};
const get = (actor, id, req) => sequelize.transaction(async (transaction) => { const row = await requireReport(actor, id, { transaction }); await audit.record({ actorId: actor.id, action: 'INFORME_VISUALIZADO', resource: 'informe', resourceId: id, context: auth.context(req), transaction }); return detail(row, actor); });
const create = (actor, data, req) => sequelize.transaction(async (transaction) => { const patient = await Paciente.findByPk(data.pacienteId, { transaction, lock: transaction.LOCK.UPDATE }); if (!patient) fail('PACIENTE_NO_ENCONTRADO', 'Paciente no encontrado.', 404); if (!patient.activo) fail('PACIENTE_INACTIVO', 'Paciente inactivo.', 422); const type = await TipoInforme.findByPk(data.tipoInformeId, { transaction }); if (!type) fail('TIPO_INFORME_NO_ENCONTRADO', 'Tipo de informe no encontrado.', 404); if (!type.activo) fail('TIPO_INFORME_INACTIVO', 'Tipo de informe inactivo.', 422); if (!policy.canCreateAny(actor) && !await linked(actor, data.pacienteId, transaction)) fail('INFORME_PACIENTE_NO_VINCULADO', 'El paciente no está vinculado.', 403); const row = await Informe.create({ ...data, autorId: actor.id, estado: 'borrador', version: 1 }, { transaction }); await audit.record({ actorId: actor.id, action: 'INFORME_CREADO', resource: 'informe', resourceId: row.id, metadata: { pacienteId: data.pacienteId, tipoInformeId: data.tipoInformeId }, context: auth.context(req), transaction }); await row.reload({ include, transaction }); return detail(row, actor); });
const update = (actor, id, data, req) => sequelize.transaction(async (transaction) => { const row = await requireReport(actor, id, { transaction, lock: transaction.LOCK.UPDATE }); await assertAuthorConditions(actor, row, transaction); const type = await TipoInforme.findByPk(data.tipoInformeId, { transaction }); if (!type) fail('TIPO_INFORME_NO_ENCONTRADO', 'Tipo de informe no encontrado.', 404); if (!type.activo && type.id !== row.tipoInformeId) fail('TIPO_INFORME_INACTIVO', 'No podés seleccionar un tipo inactivo.', 422); const [count] = await Informe.update({ tipoInformeId: data.tipoInformeId, titulo: data.titulo, resumen: data.resumen, contenido: data.contenido, version: sequelize.literal('version + 1') }, { where: { id, version: data.expectedVersion, estado: 'borrador' }, transaction }); if (!count) fail('INFORME_VERSION_CONFLICTO', 'El informe fue modificado por otra solicitud.', 409); await audit.record({ actorId: actor.id, action: 'INFORME_EDITADO', resource: 'informe', resourceId: id, metadata: { tipoInformeId: data.tipoInformeId }, context: auth.context(req), transaction }); await row.reload({ include, transaction }); return detail(row, actor); });
const finalize = (actor, id, expectedVersion, req) => sequelize.transaction(async (transaction) => { const row = await requireReport(actor, id, { transaction, lock: transaction.LOCK.UPDATE }); await assertAuthorConditions(actor, row, transaction); const [count] = await Informe.update({ estado: 'finalizado', fechaEmision: new Date(), version: sequelize.literal('version + 1') }, { where: { id, version: expectedVersion, estado: 'borrador' }, transaction }); if (!count) fail('INFORME_VERSION_CONFLICTO', 'El informe fue modificado por otra solicitud.', 409); await audit.record({ actorId: actor.id, action: 'INFORME_FINALIZADO', resource: 'informe', resourceId: id, context: auth.context(req), transaction }); await row.reload({ include, transaction }); return detail(row, actor); });
module.exports = { list, get, create, update, finalize, summary, detail };
