/** Mantiene paciente, tutor, vínculos y auditoría dentro de la misma unidad transaccional. */
const { Op, UniqueConstraintError } = require('sequelize');
const appointmentLocks = require('../turnos/turno-locks.service');
const AppError = require('../../shared/errors/AppError'); const { sequelize, Paciente, Tutor, UsuarioPaciente, Turno } = require('../../shared/database/models'); const { getPagination, paginationMeta } = require('../../shared/utils/pagination'); const { normalizeDni } = require('../../shared/utils/sanitize'); const audit = require('../auditoria/auditoria.service'); const auth = require('../auth/auth.service'); const projection = require('./paciente.projection'); const policy = require('./paciente.policy');
const tutorInclude = { model: Tutor, as: 'tutor' };
const linked = async (actor, patientId, transaction) => policy.isGlobal(actor) || Boolean(await UsuarioPaciente.findOne({ where: { usuarioId: actor.id, pacienteId: patientId, activo: true }, transaction }));
const requirePatient = async (actor, id, options = {}) => { const row = await Paciente.findByPk(id, { include: [tutorInclude], ...options }); if (!row || !(await linked(actor, id, options.transaction))) throw new AppError({ code: 'PACIENTE_NO_ENCONTRADO', message: 'Paciente no encontrado.', status: 404 }); return row; };
const check = ({ paciente, tutor }) => { if (!tutor) throw new AppError({ code: 'TUTOR_REQUERIDO', message: 'El tutor es obligatorio.', status: 422 }); const birth = new Date(paciente.fechaNacimiento); if (birth > new Date()) throw new AppError({ code: 'FECHA_NACIMIENTO_INVALIDA', message: 'La fecha de nacimiento no puede ser futura.', status: 422 }); if (paciente.poseeCud && !paciente.cudFechaVencimiento) throw new AppError({ code: 'CUD_VENCIMIENTO_REQUERIDO', message: 'La fecha de vencimiento de CUD es obligatoria.', status: 422 }); if (!paciente.poseeCud && paciente.cudFechaVencimiento) throw new AppError({ code: 'CUD_VENCIMIENTO_NO_PERMITIDO', message: 'No corresponde informar vencimiento de CUD.', status: 422 }); };
const list = async (actor, query) => { if (policy.isProfessional(actor) && (query.activo === false || (query.prestadorId && query.prestadorId !== actor.id))) throw new AppError({ code: 'FORBIDDEN_FILTER', message: 'El filtro solicitado no está permitido.', status: 403 }); const { page, limit, offset } = getPagination(query); const where = { activo: query.activo }; if (query.dni) where.dni = query.dni; if (query.search) where[Op.or] = [{ nombre: { [Op.iLike]: `%${query.search}%` } }, { apellido: { [Op.iLike]: `%${query.search}%` } }, { dni: query.search.replace(/\D/g, '') }]; const include = []; const providerId = policy.isProfessional(actor) ? actor.id : query.prestadorId; if (providerId) include.push({ model: require('../../shared/database/models').Usuario, as: 'prestadoresVinculados', where: { id: providerId }, attributes: [], through: { where: { activo: true }, attributes: [] } }); const { rows, count } = await Paciente.findAndCountAll({ where, include, distinct: true, limit, offset, order: [[query.sort, query.order.toUpperCase()], ['id', 'ASC']] }); return { data: rows.map(projection.summary), meta: paginationMeta({ page, limit, total: count }) }; };
const get = async (actor, id) => projection.detail(await requirePatient(actor, id));
const create = async (actor, data, req) => { check(data); try { return await sequelize.transaction(async (transaction) => { const patientData = { ...data.paciente, dni: data.paciente.dni ? normalizeDni(data.paciente.dni) : null, activo: true }; const row = await Paciente.create(patientData, { transaction }); await Tutor.create({ ...data.tutor, pacienteId: row.id }, { transaction }); if (policy.isProfessional(actor)) await UsuarioPaciente.create({ usuarioId: actor.id, pacienteId: row.id, vinculadoPor: actor.id, fechaInicio: new Date() }, { transaction }); await audit.record({ actorId: actor.id, action: 'PACIENTE_CREADO', resource: 'paciente', resourceId: row.id, context: auth.context(req), transaction }); await row.reload({ include: [tutorInclude], transaction }); const possible = !row.dni && await Paciente.count({ where: { id: { [Op.ne]: row.id }, dni: null, nombre: { [Op.iLike]: row.nombre }, apellido: { [Op.iLike]: row.apellido }, fechaNacimiento: row.fechaNacimiento }, transaction }); return { data: projection.detail(row), warnings: possible ? [{ code: 'PACIENTE_POSIBLE_DUPLICADO', message: 'Existe otro paciente con datos coincidentes.' }] : [] }; }); } catch (error) { if (error instanceof UniqueConstraintError) throw new AppError({ code: 'PACIENTE_DNI_DUPLICADO', message: 'El DNI ya está registrado.', status: 409 }); throw error; } };
const update = async (actor, id, data, req) => { check(data); try { return await sequelize.transaction(async (transaction) => { const row = await requirePatient(actor, id, { transaction, lock: transaction.LOCK.UPDATE }); await row.update({ ...data.paciente, dni: data.paciente.dni ? normalizeDni(data.paciente.dni) : null }, { transaction }); await row.tutor.update(data.tutor, { transaction }); await audit.record({ actorId: actor.id, action: 'PACIENTE_EDITADO', resource: 'paciente', resourceId: id, context: auth.context(req), transaction }); return projection.detail(row); }); } catch (error) { if (error instanceof UniqueConstraintError) throw new AppError({ code: 'PACIENTE_DNI_DUPLICADO', message: 'El DNI ya está registrado.', status: 409 }); throw error; } };
const changeState = async (actor, id, active, req) => sequelize.transaction(async (transaction) => { if (!active) await appointmentLocks.lockRelatedTo('pacienteId', id, transaction); const row = await requirePatient(actor, id, { transaction, lock: transaction.LOCK.UPDATE }); if (row.activo === active) throw new AppError({ code: 'PACIENTE_ESTADO_SIN_CAMBIOS', message: 'El paciente ya posee ese estado.', status: 409 }); if (!active) { const count = await Turno.count({ where: { pacienteId: id, estado: { [Op.in]: ['pendiente', 'confirmado'] }, inicioAt: { [Op.gt]: new Date() } }, transaction }); if (count) throw new AppError({ code: 'PACIENTE_TIENE_TURNOS_FUTUROS', message: 'El paciente tiene turnos futuros.', status: 409 }); } await row.update({ activo: active }, { transaction }); await audit.record({ actorId: actor.id, action: active ? 'PACIENTE_ACTIVADO' : 'PACIENTE_DESACTIVADO', resource: 'paciente', resourceId: id, context: auth.context(req), transaction }); return projection.detail(row); });
module.exports = { list, get, create, update, changeState, requirePatient, linked };
